name: E2E Regression

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [master, main]

env:
  TARGET: "%regex[.*Tests.*],com.automationexercices.tests.**.**,com.automationexercices.tests.**"

jobs:
  Chrome_Linux_Test:
    # تشغيل هذا ال job فقط إذا نجح workflow المشروع A
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout Code
        uses: actions/checkout@v5

      - name: Check Trigger Details
        run: |
            echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "Workflow Run Event: ${{ github.event.workflow_run.event }}"
            echo "Workflow Name: ${{ github.event.workflow_run.name }}"  

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn -Dtest="${TARGET}" -DexecutionType="LocalHeadless"  -DbrowserType="Chrome" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v5
        with:
          name: Chrome_Linux_Report
          path: "test-output/reports/*.html"

  Edge_Windows_Test:
    # تشغيل هذا ال job فقط إذا نجح workflow المشروع A
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout Code
        uses: actions/checkout@v5

      - name: Check Trigger Details
        run: |
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow Run Event: ${{ github.event.workflow_run.event }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn -Dtest="${TARGET}" -DexecutionType="LocalHeadless"  -DbrowserType="Edge" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v5
        with:
          name: Edge_Windows_Report
          path: "test-output/reports/*.html"