name: E2E Regression

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '00 21 * * *'
  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],com.automationexercices.tests.**.**,com.automationexercices.tests.**"

jobs:

  Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write

    steps:

      # -----------------------------------------------------
      # Checkout the repository
      # -----------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4


      # -----------------------------------------------------
      # Node + Angular
      # -----------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Angular Dependencies
        working-directory: POS-19-10-2025/POSFront
        run: npm install

      - name: Start Angular Server (background)
        working-directory: POS-19-10-2025/POSFront
        shell: pwsh
        run: |
          Start-Job -ScriptBlock { npm start }
          Start-Sleep -Seconds 15

      - name: Wait until Angular is running
        shell: pwsh
        run: |
          $max = 30
          for ($i=0; $i -lt $max; $i++) {
            try {
              Invoke-WebRequest -Uri "http://localhost:4200" -UseBasicParsing | Out-Null
              Write-Host "Angular Frontend is UP!"
              exit 0
            } catch {
              Write-Host "Waiting for Angular..."
              Start-Sleep -Seconds 3
            }
          }
          Write-Host "Angular FAILED to start!"
          exit 1


      # -----------------------------------------------------
      # Java + Maven + Selenium
      # -----------------------------------------------------
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Run Selenium Tests (Edge)
        run: mvn -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="Edge" clean test


      # -----------------------------------------------------
      # Upload Reports
      # -----------------------------------------------------
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Edge_Windows_Report
          path: test-output/reports/*.html
